### ISSUE TITLE
Working build for mac and other improvements

### ISSUE THREAD

**Issue by christosnc** [Ataraxia-Mechanica/InfiniSweeper#3]
Hello,

I managed to build the app on macos m1, here are the instructions:

1. Install cmake with homebrew: `brew install cmake`
2. Clone repository and cd into it
3. Find and add all the dependencies in the vendors folder
4. In src/atlas.cpp, replace `#include <glad/gl.h>` with `#include <OpenGL/gl3.h>`
5. run `cmake .`
6. run `cmake --build .`
7. run `./bin/InfiniSweeper`

That's all!

Now please consider adding the dependencies in the repository so we don't have to go to a scavenger hunt..
(You can add them as sub-repos)

Also, regarding the board generation algorithm, I would suggest a major improvement, which always guarantees solvable puzzles with no guesses. The best algorithm I know of is of Simon Tatham's "Mines" puzzle. It's written in C so that's a plus. The basic outline is that you have rules, just like a human would use to solve it, and when the user clicks on their first box, you start the generation. Now you begin with randomly chosen numbers, and progress from that. If you reach a deadlock, you modify the board and proceed. That's an oversimplification to say the least, but maybe someone is willing to have a look at it!

Thanks!

**Comment by Ataraxia-Mechanica** [comment]
Mac build's not gonna be a thing anytime soon because VMware just annihilated my windows installation with its janky network driver and I don't have a spare usb stick as a bootable drive

**Comment by Ataraxia-Mechanica** [comment]
✓ Mac build
✓ Add dependencies
× No-guess board (I've taken a look at their code and i think it's way out of my league to implement something like that. It's quite low level and long, the board generation part has 1500 lines which is as many as the LOC of this entire game (not including header files). I'm an amateur programmer and it's a miracle that this game even works.)
